builds:
  - main: main.go
    binary: adopt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - completion.yaml
      - scripts/install_plugin.sh
