name: "adopt"
version: "0.3.0"
usage: "Adopt k8s resources into a helm chart"
description: "Adopt k8s resources into a helm chart"
command: "$HELM_PLUGIN_DIR/bin/adopt"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
